export {default as Home} from '../screens/Home/Home'
export {default as Photoview} from './Photoview/Photoview'
export {default as Profile} from '../screens/Profile/Profile'
export {default as Favorites} from '../screens/Favorites/Favorites'
export {default as Category} from '../screens/Category/Category'
export {default as Orientation} from '../screens/Orientation/Orientation'
export {default as Authen} from '../screens/Authenticate/Authen'