export default ({
    LOGO: require('../assets/icons/logo.png'),
    LOGO_TRANS: require('../assets/icons/logo_trans.png'),
    PROFILE: require('../assets/icons/user.png'),
    FB_LOGO: require('../assets/icons/btnFb.png'),
    GG_LOGO: require('../assets/icons/btnGg.png'),
    ARROW_GO: require('../assets/icons/go-arrow.png'),
    DARK_ARROW_GO: require('../assets/icons/go-arrow-dark.png'),
    DARK_FB_LOGO:  require('../assets/icons/dark_fb_logo.png'),
    DARK_GG_LOGO:  require('../assets/icons/dark_gg_logo.png'),
    OKAY: require('../assets/icons/okay.png'),
    EDIT: require('../assets/icons/edit.png'),
    HOME: require('../assets/icons/icon_home.png'),
    LIKES: require('../assets/icons/likes.png'),
    VIEWS: require('../assets/icons/views.png'),
    DOWNLOADS : require('../assets/icons/download.png'),
    SHARE : require('../assets/icons/share.png'),
    NEXT: require('../assets/icons/next.png'),
    PREV: require('../assets/icons/prev.png'),
    USER_PROFILE: require('../assets/icons/profile.png'),
    SEARCH : require('../assets/icons/search.png'),
    FAVORITES : require('../assets/icons/favorites.png'),
    CLOSE   : require('../assets/icons/close.png'),
})