
export default ({
    IMAGE_CATEGORY: [require('../assets/images/backgrounds.jpg'),
    require('../assets/images/fashion.jpg'),
    require('../assets/images/nature.jpg'),
    require('../assets/images/sience.jpg'),
    require('../assets/images/education.jpg'),
    require('../assets/images/feelings.jpg'),
    require('../assets/images/health.jpg'),
    require('../assets/images/people.jpg'),
    require('../assets/images/religion.jpg'),
    require('../assets/images/places.jpg'),
    require('../assets/images/animals.jpg'),
    require('../assets/images/industry.jpg'),
    require('../assets/images/computer.jpg'),
    require('../assets/images/food.jpg'),
    require('../assets/images/sports.jpg'),
    require('../assets/images/transportation.jpg'),
    require('../assets/images/travel.jpg'),
    require('../assets/images/buildings.jpg'),
    require('../assets/images/business.jpg'),
    require('../assets/images/music.jpg'),],
    IMAGE_ORIENTATION: [
        require('../assets/images/vertical.jpg'),
        require('../assets/images/horizontal.jpg'),
    ],

    IMAGE_GRADIENT: [require('../assets/images/gradient_1.jpg'),
    require('../assets/images/gradient_2.jpg'),
    require('../assets/images/gradient_3.jpg'),
    require('../assets/images/gradient_4.jpg'),],

    ORIENTATION: require('../assets/images/orientation.jpg'),
    VERTICAL: require('../assets/images/vertical.jpg'),
    HORIZONTAL: require('../assets/images/horizontal.jpg'),

    BG_BLUR: [require('../assets/images/blur_1.jpg'),
    require('../assets/images/blur_2.jpg'),
    require('../assets/images/blur_3.jpg'),
    require('../assets/images/blur_4.jpg'),
    require('../assets/images/blur_5.jpg'),
    require('../assets/images/blur_6.jpg'),
    require('../assets/images/blur_7.jpg'),
    require('../assets/images/blur_8.jpg'),],
})