export default ({
    REGISTER        :   'REGISTER',
    LOGIN           :   'LOGIN',
    SUCCESSFULLY    :   'SUCCESSFULLY',
    DONE            :   'DONE',
    AGAIN           :   'AGAIN',

    FNAME           :   'First name',
    LNAME           :   'Last name',
    PHONE           :   'Phone number',
    MAIL            :   'Mail Address',
    PASSWORD        :   'Password',
    CPASSWORD       :   'Comfirm Password',
    GENDER          :   'Gender',
    GENDER_VALUE    :   ['Male','Female'],
    HAVE_ACCOUNT    :   'Have an account?',
    LOGIN_NOW       :   'Login now',
    NO_ACCOUNT      :   'No account ?',
    JOIN_NOW        :   'Join now',

    YOU_NOT_LOGGED  :   'You are not logged in',
    LOGIN_W_FB      :   'Login with Facebook',
    LOGIN_W_GG      :   'Login with Google',
    GO              :   'GO',
    REMEMBER_ME     :   'Remember me',
    SIGNOUT         :   'Sign Out',
    WELCOME         :   'WELCOME\nBACK!',
    CREATE_ACCOUNT  :   'CREATE\nACCOUNT',
    REGISTERED      :   'Your account has create sucessfully!',
    CHANGE_PASSWORD :   'Change password',
    UPDATE          :   'UPDATE',
    PW_NOT_MATCH    :   'Password and Confirm password do not match!',
    PW_IS_CHANGED   :   'Password is changed',
    NEW_PW          :   'New password',
    NEW_C_PW        :   'New confirm password',
    UPDATE_Y_NAME   :   'Update your name',
    UPLOAD_PHOTO    :   'Upload Photo',
    UPLOAD_THIS_PHOTO    :   'Upload This Photo',
    CHOOSE_NEW_PICTURE: 'Choose Your New Picture Photo',
    TAKE_PHOTO      :   'Take new photo',
    FROM_LIBRARY    :   'Choose from Library',
    CANCEL          :   'Cancel',
    VIEW_PHOTO      :   'View photo',
    DARK_MODE       :   'Dark mode',
    SAFE_SEARCH     :   'Safe search',
    LANGUAGE        :   'Language (VI/EN)',
    SEARCHING       :   'Searching...',
    FORGET_PW       :   'Reset password',
    NEED_HELP       :   'Need help ?',
    ABOUT_APP       :   'About app',
    SUBMIT          :   'Send Mail Recovery Password',
RECOVERYMAIL_SENDED :   'An email with a password reset link has been sent to you\nPlease check your mailbox and follow the instructions',

})  